import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "keen-slider/keen-slider.min.css";
import Footer from "@/components/footer";
import NavigationMenu from "@/components/navigationMenu";
import Logo from "@/components/ui/logo";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-arial antialiased`}>
        <nav className="h-22 px-20 flex items-center justify-between">
          <Logo />
          <NavigationMenu />
        </nav>
        {children}
        <Footer />
      </body>
    </html>
  );
}
