import type { Metadata } from "next";
import "./globals.css";
import "keen-slider/keen-slider.min.css";
import Footer from "@/components/footer";
import NavigationMenu from "@/components/navigationMenu";
import Logo from "@/components/ui/logo";

import { ProductSelectionProvider } from "@/context/ProductSelectionContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProductSelectionProvider>
      <html lang="en">
        <body className="font-arial flex min-h-screen flex-col antialiased">
          <nav className="flex h-22 items-center justify-between px-20">
            <Logo />
            <NavigationMenu />
          </nav>
          {children}
          <Footer />
        </body>
      </html>
    </ProductSelectionProvider>
  );
}
